### ISSUE TITLE
How to implement nested SliverList? 

### ISSUE THREAD

**Issue by erfanium** [letsar/flutter_sticky_header#66]
First I use this example from here: 
https://github.com/letsar/flutter_sticky_header/blob/master/example/lib/examples/mix_slivers.dart

Instead of hard-coded `_StickyHeaderList` in build method:
https://github.com/letsar/flutter_sticky_header/blob/ea97f5455a7eb52899a15cd9aed0b79286648963/example/lib/examples/mix_slivers.dart#L12-L35

 I want to use another ListView like:
```dart
  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'List Example',
      slivers: [
        SliverAppBar(
          backgroundColor: Colors.orange,
          title: Text('SliverAppBar'),
          automaticallyImplyLeading: false,
          pinned: true,
        ),
        SliverToBoxAdapter(
          child: Container(
            height: 50,
            color: Colors.red,
          ),
        ),
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (context, i) => ListTile(
              leading: _StickyHeaderList(),
            ),
            childCount: 6,
          ),
        ),
      ],
    );
  }
}
```

But I get this error:
```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:36721/dart_sdk.js:5031:11)
    at Object.nullCheck (http://localhost:36721/dart_sdk.js:5356:30)
    at viewport.RenderViewport.new.hitTestChildren (http://localhost:36721/packages/flutter/src/rendering/sliver.dart.lib.js:2018:31)

```

How can I do that?

**Comment by letsar** [comment]
What do you want to achieve exactly? Here you provide a Sliver to the leading of the ListTile, that's why there is an error.
